#pragma once
//#define __GXX_TYPEINFO_EQUALITY_INLINE 1
//#undef __GXX_TYPEINFO_EQUALITY_INLINE
#include <typeinfo>
#include <iostream>
#include <iomanip>
#include <sstream>
#include <chrono>
#include <format>
#include <string>
#include <vector>
#include <list>
#include <set>
#include <memory>
#include <thread>
#include <limits>
#include <random>
#include <stdexcept>
#include <SFML/Audio.hpp>
#include <SFML/Network.hpp>
#include <SFML/Window.hpp>
#include <concepts>
#include <cstdint>
#include <type_traits>
#include <map>
#include <unordered_map>